name: Build Documentation

on:
  push:
    branches:
    - main
    paths-ignore:
      - README.md
      - Dockerfile
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Install Sphinx theme
      run: pip install sphinx-rtd-theme

    - name: Build and Commit
      uses: sphinx-notes/pages@v2
      
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages